#!/bin/bash

SCALEIO_SERVERS="scaleio1.example.com scaleio2.example.com scaleio3.example.com"
SCALEIO_PW="SCALEIO_ADMIN_PASSWORD"

show_help() { 
	echo -e "\nThis script will snapshot a given volume name, first deleting the oldest snapshot if 31 snapshots already exist."
	echo -e "\nUsage:  snapshot_volume [OPTIONS] (-n volume_name) \n" 
	echo "OPTIONS:" 
	echo " -h, -?   help" 
	echo " -i       display only then new shapshot_ID upon success" 
	echo " -n       ScaleIO volume_name to snapshot" 
	echo -e " -v       increase verbosity\n" 
        exit 1
} 

OPTIND=1
VOLUME_NAME=
ID_ONLY=0
VERBOSE=0

while getopts "h?in:v" opt; do
    case "$opt" in
    h|\?)
        show_help
        exit 0
        ;;
    i)  ID_ONLY=1
        ;;
    n)  VOLUME_NAME=$OPTARG
        ;;
    v)  VERBOSE=1
        ;;
    esac
done

shift $((OPTIND-1))

if [ "${VOLUME_NAME}" == "" ] 
then 
	show_help
	exit 1
fi 

#Find out which server is our current primary MDM
PRIMARY_SERVER=
for SERVER in ${SCALEIO_SERVERS}; do
  OUTPUT=$(ssh ${SERVER} "scli --login --username admin --password ${SCALEIO_PW} 2>&1") 
  #Error: Failed to connect
  #Logged in. User role is SuperUser. System ID is 78221ddb0dcff2f5
  WORKED=$(echo "${OUTPUT}" | grep 'Logged in')
  if [ $? -eq 0 ]; then
    PRIMARY_SERVER=${SERVER}
    break
  fi
done

if [ "${PRIMARY_SERVER}" != "" ]; then
  if [ ${VERBOSE} -eq 1 ]; then echo -e "Found primary ScaleIO MDM ${PRIMARY_SERVER}\n"; fi
  OUTPUT=$(ssh ${PRIMARY_SERVER} "scli --query_all_volume") 
  WORKED=$(echo "${OUTPUT}" | grep "Name: ${VOLUME_NAME}") 
  if [ $? -eq 0 ]; then
    SNAPSHOTS=$(echo "${OUTPUT}" | grep "Snapshot of ${VOLUME_NAME}")
    SNAP_COUNT=$(echo "${SNAPSHOTS}" | wc -l)
    if [ "${SNAP_COUNT}" == "31" ]; then
      OLDEST_SNAP=$(echo "${SNAPSHOTS}" | awk '{print $3}' | sort | head -1)
      OUTPUT=$(ssh ${PRIMARY_SERVER} "scli --remove_volume --volume_id ${OLDEST_SNAP} --i_am_sure")
      if [ ${VERBOSE} -eq 1 ]; then echo -e "Removing oldest snapshot as 31 currently exist.\n${OUTPUT}\n"; fi
      sleep 3
      OUTPUT=$(ssh ${PRIMARY_SERVER} "scli --snapshot_volume --volume_name ${VOLUME_NAME}")
      if [ ${ID_ONLY} -eq 0 ]; then echo -e "${OUTPUT}\n"; fi
      if [ ${ID_ONLY} -eq 1 ]; then echo "${OUTPUT}" | awk '/=>/ {print $NF}'; fi
    else
      OUTPUT=$(ssh ${PRIMARY_SERVER} "scli --snapshot_volume --volume_name ${VOLUME_NAME}")
      if [ ${ID_ONLY} -eq 0 ]; then echo -e "${OUTPUT}\n"; fi
      if [ ${ID_ONLY} -eq 1 ]; then echo "${OUTPUT}" | awk '/=>/ {print $NF}'; fi
    fi
  else
    (>&2 echo -e "\n${OUTPUT}\nERROR: Volume name ${VOLUME_NAME} not found."); exit 1
  fi
else
  (>&2 echo "ERROR: Could not determine the primary ScaleIO MDM server. Aborting."); exit 1
fi
